# ══════════════════════════════════════════════════════════════════════════════
# 🐳 Docker Compose - ft_transcendence
# ══════════════════════════════════════════════════════════════════════════════

services:
  db:
    container_name: pixie_pong
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Testing container, so our real data will not be corrupt.
  db_test:
    container_name: test_pong
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - .env.test
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_test:
